server:
  port: 8010
#
spring:
  freemarker:
    check-template-location: false
  profiles:
    active: dev
  jackson:
    time-zone: GMT+8
  redis:
      #数据库索引
      database: ${REDIS_DB:0}
      host: ${REDIS_HOST:127.0.0.1}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PWD:}
      #连接超时时间
      timeout: 5000
